version: '3.8'

services:
  flask_app:
    build:
      context: .
    container_name: flask_app
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask_app